/** Public surface of the analysis feature — nothing outside it should reach deeper. */
export { analysisKeys, getAnalysis } from './api';
export { useAnalysis, useAnalysisErrorMessage } from './hooks';
export { ANALYSIS_WINDOWS, AnalysisErrorCode } from './types';
export type {
  AnalysisGoal,
  AnalysisHabit,
  AnalysisReport,
  AnalysisThresholds,
  AnalysisUnit,
  AnalysisWindow,
  Automaticity,
  Basis,
  Cadence,
  CalendarTally,
  Correlation,
  CorrelationStrength,
  Coverage,
  Formation,
  FormationStage,
  HeatCell,
  Highlight,
  HighlightKind,
  HighlightTone,
  MoodBand,
  MoodDirection,
  MoodDistribution,
  MoodPerformance,
  OutcomeMix,
  Regularity,
  RegularityBand,
  Series,
  SeriesPoint,
  SeriesStep,
  Setup,
  Trend,
  TrendDirection,
  TrendHalf,
  WeekdayCell,
  WeekdayExtremes,
} from './types';
